# Generated by Django 5.2.2 on 2025-06-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="deleted",
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
